"""Reference lookups for geographic and industry labels.

This module holds *metadata only* (region and OKVED code labels); it never
touches the data. It is the pandas port of the "Справочник регионов" (region
reference) that the original Excel analysis used to turn FNS region codes into
readable names. The mappings are the standard public FNS / OKVED2 references.

Labels are used exclusively for presentation (tables, figures). Statistically
relevant behaviour must not depend on these names — codes are always used for
grouping.
"""

# FNS region code -> region name (Russian). Codes present in the raw register.
REGION_NAMES_RU = {
    "00": "Не определён (служебная строка)",
    "01": "Республика Адыгея",
    "02": "Республика Башкортостан",
    "03": "Республика Бурятия",
    "04": "Республика Алтай",
    "05": "Республика Дагестан",
    "06": "Республика Ингушетия",
    "07": "Кабардино-Балкарская Республика",
    "08": "Республика Калмыкия",
    "09": "Карачаево-Черкесская Республика",
    "10": "Республика Карелия",
    "11": "Республика Коми",
    "12": "Республика Марий Эл",
    "13": "Республика Мордовия",
    "14": "Республика Саха (Якутия)",
    "15": "Республика Северная Осетия — Алания",
    "16": "Республика Татарстан",
    "17": "Республика Тыва",
    "18": "Удмуртская Республика",
    "19": "Республика Хакасия",
    "20": "Чеченская Республика",
    "21": "Чувашская Республика",
    "22": "Алтайский край",
    "23": "Краснодарский край",
    "24": "Красноярский край",
    "25": "Приморский край",
    "26": "Ставропольский край",
    "27": "Хабаровский край",
    "28": "Амурская область",
    "29": "Архангельская область",
    "30": "Астраханская область",
    "31": "Белгородская область",
    "32": "Брянская область",
    "33": "Владимирская область",
    "34": "Волгоградская область",
    "35": "Вологодская область",
    "36": "Воронежская область",
    "37": "Ивановская область",
    "38": "Иркутская область",
    "39": "Калининградская область",
    "40": "Калужская область",
    "41": "Камчатский край",
    "42": "Кемеровская область",
    "43": "Кировская область",
    "44": "Костромская область",
    "45": "Курганская область",
    "46": "Курская область",
    "47": "Ленинградская область",
    "48": "Липецкая область",
    "49": "Магаданская область",
    "50": "Московская область",
    "51": "Мурманская область",
    "52": "Нижегородская область",
    "53": "Новгородская область",
    "54": "Новосибирская область",
    "55": "Омская область",
    "56": "Оренбургская область",
    "57": "Орловская область",
    "58": "Пензенская область",
    "59": "Пермский край",
    "60": "Псковская область",
    "61": "Ростовская область",
    "62": "Рязанская область",
    "63": "Самарская область",
    "64": "Саратовская область",
    "65": "Сахалинская область",
    "66": "Свердловская область",
    "67": "Смоленская область",
    "68": "Тамбовская область",
    "69": "Тверская область",
    "70": "Томская область",
    "71": "Тульская область",
    "72": "Тюменская область",
    "73": "Ульяновская область",
    "74": "Челябинская область",
    "75": "Забайкальский край",
    "76": "Ярославская область",
    "77": "Город Москва",
    "78": "Город Санкт-Петербург",
    "79": "Еврейская автономная область",
    "83": "Ненецкий автономный округ",
    "86": "Ханты-Мансийский автономный округ — Югра",
    "87": "Чукотский автономный округ",
    "89": "Ямало-Ненецкий автономный округ",
    "90": "Запорожская область",
    "91": "Республика Крым",
    "92": "Город Севастополь",
    "93": "Донецкая Народная Республика",
    "94": "Луганская Народная Республика",
    "95": "Херсонская область",
}

# FNS region code -> English name (used in figures / outputs).
REGION_NAMES_EN = {
    "00": "Undefined (service row)",
    "01": "Republic of Adygea",
    "02": "Republic of Bashkortostan",
    "03": "Republic of Buryatia",
    "04": "Republic of Altai",
    "05": "Republic of Dagestan",
    "06": "Republic of Ingushetia",
    "07": "Kabardino-Balkar Republic",
    "08": "Republic of Kalmykia",
    "09": "Karachay-Cherkess Republic",
    "10": "Republic of Karelia",
    "11": "Republic of Komi",
    "12": "Republic of Mari El",
    "13": "Republic of Mordovia",
    "14": "Republic of Sakha (Yakutia)",
    "15": "Republic of North Ossetia-Alania",
    "16": "Republic of Tatarstan",
    "17": "Republic of Tuva",
    "18": "Udmurt Republic",
    "19": "Republic of Khakassia",
    "20": "Chechen Republic",
    "21": "Chuvash Republic",
    "22": "Altai Krai",
    "23": "Krasnodar Krai",
    "24": "Krasnoyarsk Krai",
    "25": "Primorsky Krai",
    "26": "Stavropol Krai",
    "27": "Khabarovsk Krai",
    "28": "Amur Oblast",
    "29": "Arkhangelsk Oblast",
    "30": "Astrakhan Oblast",
    "31": "Belgorod Oblast",
    "32": "Bryansk Oblast",
    "33": "Vladimir Oblast",
    "34": "Volgograd Oblast",
    "35": "Vologda Oblast",
    "36": "Voronezh Oblast",
    "37": "Ivanovo Oblast",
    "38": "Irkutsk Oblast",
    "39": "Kaliningrad Oblast",
    "40": "Kaluga Oblast",
    "41": "Kamchatka Krai",
    "42": "Kemerovo Oblast",
    "43": "Kirov Oblast",
    "44": "Kostroma Oblast",
    "45": "Kurgan Oblast",
    "46": "Kursk Oblast",
    "47": "Leningrad Oblast",
    "48": "Lipetsk Oblast",
    "49": "Magadan Oblast",
    "50": "Moscow Oblast",
    "51": "Murmansk Oblast",
    "52": "Nizhny Novgorod Oblast",
    "53": "Novgorod Oblast",
    "54": "Novosibirsk Oblast",
    "55": "Omsk Oblast",
    "56": "Orenburg Oblast",
    "57": "Oryol Oblast",
    "58": "Penza Oblast",
    "59": "Perm Krai",
    "60": "Pskov Oblast",
    "61": "Rostov Oblast",
    "62": "Ryazan Oblast",
    "63": "Samara Oblast",
    "64": "Saratov Oblast",
    "65": "Sakhalin Oblast",
    "66": "Sverdlovsk Oblast",
    "67": "Smolensk Oblast",
    "68": "Tambov Oblast",
    "69": "Tver Oblast",
    "70": "Tomsk Oblast",
    "71": "Tula Oblast",
    "72": "Tyumen Oblast",
    "73": "Ulyanovsk Oblast",
    "74": "Chelyabinsk Oblast",
    "75": "Zabaykalsky Krai",
    "76": "Yaroslavl Oblast",
    "77": "Moscow",
    "78": "Saint Petersburg",
    "79": "Jewish Autonomous Oblast",
    "83": "Nenets Autonomous Okrug",
    "86": "Khanty-Mansi Autonomous Okrug - Yugra",
    "87": "Chukotka Autonomous Okrug",
    "89": "Yamalo-Nenets Autonomous Okrug",
    "90": "Zaporozhye Oblast",
    "91": "Republic of Crimea",
    "92": "Sevastopol",
    "93": "Donetsk People's Republic",
    "94": "Luhansk People's Republic",
    "95": "Kherson Oblast",
}

# Two-digit OKVED2 class -> short English description (figure / table labels).
OKVED_NAMES_EN = {
    "01": "Crop and animal production",
    "02": "Forestry and logging",
    "03": "Fishing and aquaculture",
    "05": "Mining of coal and lignite",
    "06": "Extraction of crude petroleum and natural gas",
    "08": "Other mining and quarrying",
    "09": "Mining support services",
    "10": "Manufacture of food products",
    "11": "Manufacture of beverages",
    "12": "Manufacture of tobacco products",
    "13": "Manufacture of textiles",
    "14": "Manufacture of wearing apparel",
    "15": "Manufacture of leather and related products",
    "16": "Wood processing",
    "17": "Manufacture of paper and paper products",
    "18": "Printing and reproduction of recorded media",
    "19": "Manufacture of coke and refined petroleum products",
    "20": "Manufacture of chemicals and chemical products",
    "21": "Manufacture of pharmaceutical products",
    "22": "Manufacture of rubber and plastic products",
    "23": "Other non-metallic mineral products",
    "24": "Manufacture of basic metals",
    "25": "Manufacture of fabricated metal products",
    "26": "Manufacture of computer, electronic and optical products",
    "27": "Manufacture of electrical equipment",
    "28": "Manufacture of machinery and equipment n.e.c.",
    "29": "Manufacture of motor vehicles and trailers",
    "30": "Manufacture of other transport equipment",
    "31": "Manufacture of furniture",
    "32": "Other manufacturing",
    "33": "Repair and installation of machinery and equipment",
    "35": "Electricity, gas, steam and air conditioning supply",
    "36": "Water collection, treatment and supply",
    "37": "Sewerage",
    "38": "Waste collection, treatment and disposal",
    "39": "Remediation activities",
    "41": "Construction of buildings",
    "42": "Civil engineering",
    "43": "Specialised construction activities",
    "45": "Sale and repair of motor vehicles and motorcycles",
    "46": "Wholesale trade",
    "47": "Retail trade",
    "49": "Land transport and pipeline transport",
    "50": "Water transport",
    "51": "Air transport",
    "52": "Warehousing and transport support activities",
    "53": "Postal and courier activities",
    "55": "Accommodation",
    "56": "Food and beverage service activities",
    "58": "Publishing activities",
    "59": "Motion picture, video and television production",
    "60": "Programming and broadcasting activities",
    "61": "Telecommunications",
    "62": "Computer programming, consultancy and related activities",
    "63": "Information service activities",
    "64": "Financial service activities, except insurance and pension funding",
    "65": "Insurance, reinsurance and pension funding",
    "66": "Auxiliary financial services",
    "68": "Real estate activities",
    "69": "Legal and accounting activities",
    "70": "Management consultancy activities",
    "71": "Architectural and engineering activities",
    "72": "Scientific research and development",
    "73": "Advertising and market research",
    "74": "Other professional, scientific and technical activities",
    "75": "Veterinary activities",
    "77": "Rental and leasing activities",
    "78": "Employment activities",
    "79": "Travel agency and reservation services",
    "80": "Security and investigation activities",
    "81": "Services to buildings and landscape activities",
    "82": "Office administrative and business support activities",
    "84": "Public administration and defence; compulsory social security",
    "85": "Education",
    "86": "Human health activities",
    "87": "Residential care activities",
    "88": "Social work activities without accommodation",
    "90": "Creative, arts and entertainment activities",
    "91": "Libraries, archives, museums and other cultural activities",
    "92": "Gambling and betting activities",
    "93": "Sports activities and amusement and recreation",
    "94": "Activities of membership organisations",
    "95": "Repair of computers, personal and household goods",
    "96": "Other personal service activities",
    "97": "Activities of households as employers",
    "99": "Activities of extraterritorial organisations and bodies",
}


def region_name_ru(code: str) -> str:
    """Russian region label for an FNS region code, with a safe fallback."""
    return REGION_NAMES_RU.get(code, f"FNS region {code}")


def region_name_en(code: str) -> str:
    """English region label for an FNS region code, with a safe fallback."""
    return REGION_NAMES_EN.get(code, f"FNS region {code}")


def okved_name_en(code: str) -> str:
    """Short English description for a two-digit OKVED2 class."""
    return OKVED_NAMES_EN.get(code, f"OKVED {code}")